[package]
name = "common_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#链路追踪-日志
tracing = "0.1.40"
#用于订阅正在发生的日志、监控事件
tracing-subscriber = {version = "0.3.17", features = ["env-filter"] }